on: push
name: Test, Build and Release apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.5'
    - run: flutter pub get
    - run: flutter build apk
    - run: flutter build appbundle
    
    - uses: actions/upload-artifact@master
      with:
        name: apk-build
        path: build/app/outputs/apk/release
        
  upload-apk:
    name: Download APK
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3.0.0
        with:
          name: apk-build
          path: build/app/outputs/apk/release
      - name: Display structure of downloaded files
        run: ls -R
          
